// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderEvent = `-- name: CreateOrderEvent :execrows
INSERT INTO order_events (
    event_id,
    command_id,
    command_sequence,
    event_index,
    order_id,
    user_id,
    ticker,
    event_type,
    reason,
    order_type,
    side,
    previous_price,
    price,
    previous_amount,
    filled_amount,
    canceled_amount,
    remaining_amount,
    occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18
)
ON CONFLICT (event_id) DO NOTHING
`

type CreateOrderEventParams struct {
	EventID         string             `db:"event_id" json:"event_id"`
	CommandID       string             `db:"command_id" json:"command_id"`
	CommandSequence int64              `db:"command_sequence" json:"command_sequence"`
	EventIndex      int32              `db:"event_index" json:"event_index"`
	OrderID         string             `db:"order_id" json:"order_id"`
	UserID          string             `db:"user_id" json:"user_id"`
	Ticker          string             `db:"ticker" json:"ticker"`
	EventType       string             `db:"event_type" json:"event_type"`
	Reason          string             `db:"reason" json:"reason"`
	OrderType       string             `db:"order_type" json:"order_type"`
	Side            string             `db:"side" json:"side"`
	PreviousPrice   float64            `db:"previous_price" json:"previous_price"`
	Price           float64            `db:"price" json:"price"`
	PreviousAmount  float64            `db:"previous_amount" json:"previous_amount"`
	FilledAmount    float64            `db:"filled_amount" json:"filled_amount"`
	CanceledAmount  float64            `db:"canceled_amount" json:"canceled_amount"`
	RemainingAmount float64            `db:"remaining_amount" json:"remaining_amount"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateOrderEvent(ctx context.Context, arg CreateOrderEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createOrderEvent,
		arg.EventID,
		arg.CommandID,
		arg.CommandSequence,
		arg.EventIndex,
		arg.OrderID,
		arg.UserID,
		arg.Ticker,
		arg.EventType,
		arg.Reason,
		arg.OrderType,
		arg.Side,
		arg.PreviousPrice,
		arg.Price,
		arg.PreviousAmount,
		arg.FilledAmount,
		arg.CanceledAmount,
		arg.RemainingAmount,
		arg.OccurredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const orderEventPayloadMatches = `-- name: OrderEventPayloadMatches :one
SELECT (
    command_id = $2
    AND command_sequence = $3
    AND event_index = $4
    AND order_id = $5
    AND user_id = $6
    AND ticker = $7
    AND event_type = $8
    AND reason = $9
    AND order_type = $10
    AND side = $11
    AND previous_price = $12
    AND price = $13
    AND previous_amount = $14
    AND filled_amount = $15
    AND canceled_amount = $16
    AND remaining_amount = $17
    AND occurred_at = $18
) AS matches
FROM order_events
WHERE event_id = $1
`

type OrderEventPayloadMatchesParams struct {
	EventID         string             `db:"event_id" json:"event_id"`
	CommandID       string             `db:"command_id" json:"command_id"`
	CommandSequence int64              `db:"command_sequence" json:"command_sequence"`
	EventIndex      int32              `db:"event_index" json:"event_index"`
	OrderID         string             `db:"order_id" json:"order_id"`
	UserID          string             `db:"user_id" json:"user_id"`
	Ticker          string             `db:"ticker" json:"ticker"`
	EventType       string             `db:"event_type" json:"event_type"`
	Reason          string             `db:"reason" json:"reason"`
	OrderType       string             `db:"order_type" json:"order_type"`
	Side            string             `db:"side" json:"side"`
	PreviousPrice   float64            `db:"previous_price" json:"previous_price"`
	Price           float64            `db:"price" json:"price"`
	PreviousAmount  float64            `db:"previous_amount" json:"previous_amount"`
	FilledAmount    float64            `db:"filled_amount" json:"filled_amount"`
	CanceledAmount  float64            `db:"canceled_amount" json:"canceled_amount"`
	RemainingAmount float64            `db:"remaining_amount" json:"remaining_amount"`
	OccurredAt      pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) OrderEventPayloadMatches(ctx context.Context, arg OrderEventPayloadMatchesParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, orderEventPayloadMatches,
		arg.EventID,
		arg.CommandID,
		arg.CommandSequence,
		arg.EventIndex,
		arg.OrderID,
		arg.UserID,
		arg.Ticker,
		arg.EventType,
		arg.Reason,
		arg.OrderType,
		arg.Side,
		arg.PreviousPrice,
		arg.Price,
		arg.PreviousAmount,
		arg.FilledAmount,
		arg.CanceledAmount,
		arg.RemainingAmount,
		arg.OccurredAt,
	)
	var matches pgtype.Bool
	err := row.Scan(&matches)
	return matches, err
}
