// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markets.sql

package db

import (
	"context"
)

const createMarket = `-- name: CreateMarket :one
INSERT INTO markets (ticker)
VALUES ($1)
ON CONFLICT (ticker) DO NOTHING
RETURNING ticker, created_at, price_scale, quantity_scale, quote_scale,
    tick_size_units, lot_size_units, min_price_ticks, max_price_ticks,
    min_quantity_lots, max_quantity_lots, config_version
`

func (q *Queries) CreateMarket(ctx context.Context, ticker string) (Market, error) {
	row := q.db.QueryRow(ctx, createMarket, ticker)
	var i Market
	err := row.Scan(
		&i.Ticker,
		&i.CreatedAt,
		&i.PriceScale,
		&i.QuantityScale,
		&i.QuoteScale,
		&i.TickSizeUnits,
		&i.LotSizeUnits,
		&i.MinPriceTicks,
		&i.MaxPriceTicks,
		&i.MinQuantityLots,
		&i.MaxQuantityLots,
		&i.ConfigVersion,
	)
	return i, err
}

const getMarket = `-- name: GetMarket :one
SELECT ticker, created_at, price_scale, quantity_scale, quote_scale,
    tick_size_units, lot_size_units, min_price_ticks, max_price_ticks,
    min_quantity_lots, max_quantity_lots, config_version
FROM markets
WHERE ticker = $1
`

func (q *Queries) GetMarket(ctx context.Context, ticker string) (Market, error) {
	row := q.db.QueryRow(ctx, getMarket, ticker)
	var i Market
	err := row.Scan(
		&i.Ticker,
		&i.CreatedAt,
		&i.PriceScale,
		&i.QuantityScale,
		&i.QuoteScale,
		&i.TickSizeUnits,
		&i.LotSizeUnits,
		&i.MinPriceTicks,
		&i.MaxPriceTicks,
		&i.MinQuantityLots,
		&i.MaxQuantityLots,
		&i.ConfigVersion,
	)
	return i, err
}

const listMarkets = `-- name: ListMarkets :many
SELECT ticker, created_at, price_scale, quantity_scale, quote_scale,
    tick_size_units, lot_size_units, min_price_ticks, max_price_ticks,
    min_quantity_lots, max_quantity_lots, config_version
FROM markets
ORDER BY ticker
`

func (q *Queries) ListMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.Query(ctx, listMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.Ticker,
			&i.CreatedAt,
			&i.PriceScale,
			&i.QuantityScale,
			&i.QuoteScale,
			&i.TickSizeUnits,
			&i.LotSizeUnits,
			&i.MinPriceTicks,
			&i.MaxPriceTicks,
			&i.MinQuantityLots,
			&i.MaxQuantityLots,
			&i.ConfigVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
