package orderevent

import (
	"context"
	"log/slog"
)

const DefaultOutputBufferSize = 128

// PersistenceRequest carries all lifecycle events generated by one journal
// command and reports the atomic store result back to the producer.
type PersistenceRequest struct {
	Events []Event
	result chan error
}

func NewPersistenceRequest(events []Event) PersistenceRequest {
	return PersistenceRequest{
		Events: events,
		result: make(chan error, 1),
	}
}

func (r PersistenceRequest) Acknowledge(err error) {
	if r.result != nil {
		r.result <- err
	}
}

func (r PersistenceRequest) Wait() error {
	if r.result == nil {
		return ErrStoreUnavailable
	}
	return <-r.result
}

// Writer persists command-sized event batches in channel receive order.
type Writer struct {
	store Store
}

func NewWriter(store Store) *Writer {
	return &Writer{store: store}
}

func (w *Writer) Run(ctx context.Context, in <-chan PersistenceRequest) {
	for request := range in {
		var err error
		switch {
		case len(request.Events) == 0:
		case ctx.Err() != nil:
			err = ctx.Err()
		case w.store == nil:
			err = ErrStoreUnavailable
		default:
			err = w.store.SaveEvents(ctx, request.Events)
		}
		if err != nil {
			slog.Error("order event store failed", "error", err)
		}
		request.Acknowledge(err)
	}
}
