// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Market struct {
	Ticker    string             `db:"ticker" json:"ticker"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}
