// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatchLog = `-- name: CreateMatchLog :execrows
INSERT INTO match_logs (
    execution_id,
    ticker,
    price_ticks,
    amount_lots,
    quote_amount_atoms,
    market_config_version,
    maker_order_id,
    taker_order_id,
    maker_user_id,
    taker_user_id,
    maker_side,
    taker_side,
    matched_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (execution_id) DO NOTHING
`

type CreateMatchLogParams struct {
	ExecutionID         string             `db:"execution_id" json:"execution_id"`
	Ticker              string             `db:"ticker" json:"ticker"`
	PriceTicks          int64              `db:"price_ticks" json:"price_ticks"`
	AmountLots          int64              `db:"amount_lots" json:"amount_lots"`
	QuoteAmountAtoms    int64              `db:"quote_amount_atoms" json:"quote_amount_atoms"`
	MarketConfigVersion int64              `db:"market_config_version" json:"market_config_version"`
	MakerOrderID        string             `db:"maker_order_id" json:"maker_order_id"`
	TakerOrderID        string             `db:"taker_order_id" json:"taker_order_id"`
	MakerUserID         string             `db:"maker_user_id" json:"maker_user_id"`
	TakerUserID         string             `db:"taker_user_id" json:"taker_user_id"`
	MakerSide           string             `db:"maker_side" json:"maker_side"`
	TakerSide           string             `db:"taker_side" json:"taker_side"`
	MatchedAt           pgtype.Timestamptz `db:"matched_at" json:"matched_at"`
}

func (q *Queries) CreateMatchLog(ctx context.Context, arg CreateMatchLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, createMatchLog,
		arg.ExecutionID,
		arg.Ticker,
		arg.PriceTicks,
		arg.AmountLots,
		arg.QuoteAmountAtoms,
		arg.MarketConfigVersion,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MakerUserID,
		arg.TakerUserID,
		arg.MakerSide,
		arg.TakerSide,
		arg.MatchedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const matchLogPayloadMatches = `-- name: MatchLogPayloadMatches :one
SELECT (
    ticker = $2
    AND price_ticks = $3
    AND amount_lots = $4
    AND quote_amount_atoms = $5
    AND market_config_version = $6
    AND maker_order_id = $7
    AND taker_order_id = $8
    AND maker_user_id = $9
    AND taker_user_id = $10
    AND maker_side = $11
    AND taker_side = $12
    AND matched_at = $13
) AS matches
FROM match_logs
WHERE execution_id = $1
`

type MatchLogPayloadMatchesParams struct {
	ExecutionID         string             `db:"execution_id" json:"execution_id"`
	Ticker              string             `db:"ticker" json:"ticker"`
	PriceTicks          int64              `db:"price_ticks" json:"price_ticks"`
	AmountLots          int64              `db:"amount_lots" json:"amount_lots"`
	QuoteAmountAtoms    int64              `db:"quote_amount_atoms" json:"quote_amount_atoms"`
	MarketConfigVersion int64              `db:"market_config_version" json:"market_config_version"`
	MakerOrderID        string             `db:"maker_order_id" json:"maker_order_id"`
	TakerOrderID        string             `db:"taker_order_id" json:"taker_order_id"`
	MakerUserID         string             `db:"maker_user_id" json:"maker_user_id"`
	TakerUserID         string             `db:"taker_user_id" json:"taker_user_id"`
	MakerSide           string             `db:"maker_side" json:"maker_side"`
	TakerSide           string             `db:"taker_side" json:"taker_side"`
	MatchedAt           pgtype.Timestamptz `db:"matched_at" json:"matched_at"`
}

func (q *Queries) MatchLogPayloadMatches(ctx context.Context, arg MatchLogPayloadMatchesParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, matchLogPayloadMatches,
		arg.ExecutionID,
		arg.Ticker,
		arg.PriceTicks,
		arg.AmountLots,
		arg.QuoteAmountAtoms,
		arg.MarketConfigVersion,
		arg.MakerOrderID,
		arg.TakerOrderID,
		arg.MakerUserID,
		arg.TakerUserID,
		arg.MakerSide,
		arg.TakerSide,
		arg.MatchedAt,
	)
	var matches pgtype.Bool
	err := row.Scan(&matches)
	return matches, err
}
